# Generated by Django 6.0.5 on 2026-06-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_alter_pastpaper_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastpaper',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
