# Generated by Django 6.0.5 on 2026-06-12 11:40

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0005_add_lecture_slide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectureslide',
            name='slide_file',
            field=models.FileField(storage=core.storage.DynamicRawStorage(), upload_to='slides/'),
        ),
        migrations.AlterField(
            model_name='pastpaper',
            name='pdf_file',
            field=models.FileField(storage=core.storage.DynamicRawStorage(), upload_to='papers/'),
        ),
    ]
