# Generated by Django 5.1.5 on 2026-04-06 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_student_department_alter_student_enrollment_no'),
    ]

    operations = [
    ]
