# Generated by Django 6.0.5 on 2026-06-02 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_missing_student_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrollment_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
