# Generated by Django 6.0.5 on 2026-06-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-user'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.RemoveConstraint(
            model_name='course',
            name='unique_department_code',
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('department', 'code')},
        ),
    ]
