# Generated by Django 6.0.5 on 2026-06-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_department_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(default='', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
