# Generated by Django 6.0.5 on 2026-07-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='upvotes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='vibe',
            field=models.CharField(choices=[('none', 'No Vibe'), ('cramming', '🔥 Cramming'), ('confused', '😵\u200d💫 Confused'), ('acing', '🚀 Acing it'), ('chill', '☕ Chill'), ('tired', '😴 Tired'), ('curious', '🤔 Curious')], default='none', max_length=20),
        ),
    ]
