# Generated by Django 6.0.5 on 2026-06-12 11:40

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_add_course_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(storage=core.storage.DynamicRawStorage(), upload_to='books/'),
        ),
    ]
